[workspace]
resolver = "2"
members = [
    "crates/hb-pod",
    "crates/hb-formats",
    "crates/hb-world",
    "crates/hb-render",
    "crates/hb-audio",
    "crates/hb-sim",
    "crates/hb",
    "crates/hb-fly",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[profile.release]
opt-level = 3
