//! The engine's phrase table: every line the game says to you.
//!
//! `0x505c20` is three hundred entries of 36 bytes. Each is a flag, how long
//! the subtitle stays up in 16.16 seconds, and four pointers - a sound, a
//! second sound, the subtitle, and one that is null in all three hundred.
//!
//! The flag is 1 or 3, and 3 is the ones that have the second sound - almost
//! always `pause.wav`, but entry 55 pairs `engcore.wav` with `dest30.wav`.
//!
//! The second field is **not** a duration, which is what it looked like:
//! `0x454476` switches on it, and 1.0, 2.0, 3.0, 4.0 and 5.0 in 16.16 are
//! five kinds of phrase with an arm each. What it selects is not read.
//!
//! Generated by reading the table out of the image; see worklog 86. The port
//! plays a line by its number here, so a trigger that is found later has its
//! words waiting.

/// One line: what it plays, what it writes, and for how long.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Phrase {
    pub sound: &'static str,
    /// The second sound, `pause.wav` where there is one.
    pub also: &'static str,
    pub text: &'static str,
    /// The entry's kind, 1 to 5 in 16.16 (`0x454476` switches on it). It
    /// reads like a duration and is not one.
    pub seconds: u32,
}

const fn p(sound: &'static str, also: &'static str, text: &'static str, seconds: u32) -> Phrase {
    Phrase { sound, also, text, seconds }
}

/// Where the table is in the retail 1.00 image.
pub const TABLE: u32 = 0x505c20;

/// Bytes an entry.
pub const STRIDE: usize = 0x24;

/// Every line, in the engine's own order - the number is the id.
pub const PHRASES: [Phrase; 300] = [
    p("", "", "", 262144), // 0
    p("", "", "", 327680), // 1
    p("pause.wav", "", "Press ` to activate", 131072), // 2
    p("pause.wav", "", "Press 1 to activate", 131072), // 3
    p("pause.wav", "", "Press 2 to activate", 131072), // 4
    p("pause.wav", "", "Press 3 to activate", 131072), // 5
    p("pause.wav", "", "Press 4 to activate", 131072), // 6
    p("pause.wav", "", "Press 5 to activate", 131072), // 7
    p("pause.wav", "", "Press 6 to activate", 131072), // 8
    p("pause.wav", "", "Press 7 to activate", 131072), // 9
    p("pause.wav", "", "Press 8 to activate", 131072), // 10
    p("pause.wav", "", "Press 9 to activate", 131072), // 11
    p("pause.wav", "", "Press 0 to activate", 131072), // 12
    p("vul-sec.wav", "pause.wav", "Vulcan Cannon secured", 131072), // 13
    p("dc-sec.wav", "pause.wav", "Dispersion Cannon secured", 131072), // 14
    p("skl-sec.wav", "pause.wav", "Servo Kinetic Lasers secured", 131072), // 15
    p("rfl-sec.wav", "pause.wav", "RFL secured", 131072), // 16
    p("hmmr-sec.wav", "pause.wav", "Sledgehammer Rockets secured", 131072), // 17
    p("scor-sec.wav", "pause.wav", "Scorcher Missiles secured", 131072), // 18
    p("vip-sec.wav", "pause.wav", "Viper Missiles secured", 131072), // 19
    p("legn-sec.wav", "pause.wav", "Legion Missiles secured", 131072), // 20
    p("indp-sec.wav", "pause.wav", "Independence Missile secured", 131072), // 21
    p("hell-sed.wav", "pause.wav", "Hellion Missiles secured", 131072), // 22
    p("doom-sec.wav", "pause.wav", "Doomsday Mines secured", 131072), // 23
    p("cloak.wav", "", "Cloaking", 131072), // 24
    p("ergy-sec.wav", "", "", 131072), // 25
    p("messpod.wav", "", "Message Pod retrieved", 131072), // 26
    p("beacons.wav", "", "Beacons dropped", 131072), // 27
    p("objcomp.wav", "", "Objective Complete", 131072), // 28
    p("engryrs.wav", "", "Energy Restored", 131072), // 29
    p("pause.wav", "", "Dispersion Cannon not in arsenal", 131072), // 30
    p("pause.wav", "", "Rapid Fire Laser not in arsenal", 131072), // 31
    p("pause.wav", "", "Sledgehammer Rockets not in arsenal", 131072), // 32
    p("pause.wav", "", "Scorcher Missiles not in arsenal", 131072), // 33
    p("pause.wav", "", "Viper Missiles not in arsenal", 131072), // 34
    p("pause.wav", "", "Legion Missiles not in arsenal", 131072), // 35
    p("pause.wav", "", "Independence Missiles not in arsenal", 131072), // 36
    p("pause.wav", "", "Hellion Missiles not in arsenal", 131072), // 37
    p("pause.wav", "", "Doomsday Mines not in arsenal", 131072), // 38
    p("engy100.wav", "", "Main energy at 100%", 131072), // 39
    p("enlow.wav", "", "Energy low", 131072), // 40
    p("hullrpr.wav", "", "Hull Repaired", 131072), // 41
    p("hulllow.wav", "", "Hull integrity low", 131072), // 42
    p("krackdes.wav", "", "Kracken Destroyed", 131072), // 43
    p("eyrides.wav", "", "<Eyrie Boss> low", 131072), // 44
    p("chimdes.wav", "", "<Chimera Boss> low", 131072), // 45
    p("gendes.wav", "", "Generator destroyed", 131072), // 46
    p("trp-des.wav", "", "Troop transport destroyed.", 131072), // 47
    p("powmark.wav", "", "Pow camp marked", 131072), // 48
    p("rishesc.wav", "", "Rishi escorted", 131072), // 49
    p("pause.wav", "", "Rishi destroyed", 131072), // 50
    p("pause.wav", "", "Temple destroyed", 131072), // 51
    p("bionnur.wav", "", "Bion nursery destroyed", 131072), // 52
    p("factdes.wav", "", "Factory destroyed", 131072), // 53
    p("nyxsed.wav", "", "Nyx destroyed", 131072), // 54
    p("engcore.wav", "dest30.wav", "Engine core destroyed", 131072), // 55
    p("destin.wav", "", "Destruction in", 131072), // 56
    p("shiva2.wav", "", "Shiva destroyed", 131072), // 57
    p("fx4des.wav", "", "FX4 destroyed", 131072), // 58
    p("pause.wav", "", "Fly to jump zone", 131072), // 59
    p("objcomp.wav", "", "Objective complete", 131072), // 60
    p("tardest.wav", "", "Target Destroyed", 131072), // 61
    p("pause.wav", "", "Jump zone closing in", 131072), // 62
    p("pause.wav", "", "Jump zone closed", 131072), // 63
    p("powmark.wav", "", "Pow camp marked", 131072), // 64
    p("diseng.wav", "", "Cloaking disengaged", 131072), // 65
    p("hullrpr.wav", "", "Hull fully repaired", 131072), // 66
    p("BtechCap.wav", "", "Bion technology captured.", 131072), // 67
    p("comptech.wav", "", "Weapon complete...", 131072), // 68
    p("tech-int.wav", "", "Technology integrated.  Advanced weapon ready to fire.", 131072), // 69
    p("cloakEng.wav", "", "Cloaking engaged.", 131072), // 70
    p("cloakDis.wav", "", "Cloaking disengaged.", 131072), // 71
    p("engy-sec.wav", "", "Energy boost secured.", 131072), // 72
    p("engy100.wav", "", "Main energy at 100%", 131072), // 73
    p("hull-pr.wav", "", "Hull partially repaired.", 131072), // 74
    p("hull-fr.wav", "", "Hull fully restored.", 131072), // 75
    p("engy-max.wav", "", "Main energy at maximum capacity.", 131072), // 76
    p("engy-nr.wav", "", "Energy not required.", 131072), // 77
    p("hull-rnr.wav", "", "Hull undamaged.  Repairs not required.", 131072), // 78
    p("warn-wel.wav", "", "Warning!  Weapon energy low!", 131072), // 79
    p("warn-sel.wav", "", "Warning!  Shield energy low!", 131072), // 80
    p("dang-hdc.wav", "", "Danger!  Hull damage critical.", 131072), // 81
    p("dang-hil.wav", "", "Danger!  Hull integrity low.", 131072), // 82
    p("misslock.wav", "", "Enemy missile lock!", 131072), // 83
    p("tempdest.wav", "", "Warning!  Temple destroyed!", 131072), // 84
    p("messpod.wav", "", "Message pod retrieved.", 131072), // 85
    p("tardest.wav", "", "Target destroyed.", 131072), // 86
    p("accpZone.wav", "", "Mission accomplished...
Proceed to jump zone.", 131072), // 87
    p("compZone.wav", "", "Mission complete...
Proceed to jump zone.", 131072), // 88
    p("missdetc.wav", "", "Mission objective detected.", 131072), // 89
    p("objcomp.wav", "", "Objective complete.", 131072), // 90
    p("chkreach.wav", "", "Checkpoint reached.", 131072), // 91
    p("jumpzone.wav", "", "Proceed to jump zone.", 131072), // 92
    p("prisoner.wav", "", "Prisoners marked for retrieval.", 131072), // 93
    p("beaklaun.wav", "", "Beacon launched.", 131072), // 94
    p("rshi-saf.wav", "", "Rishi escorted to safety.", 131072), // 95
    p("rshi-dse.wav", "", "Rishi destroyed.", 131072), // 96
    p("shut-loc.wav", "", "Coalition shuttle craft located.", 131072), // 97
    p("shut-esc.wav", "", "Coalition shuttle craft escaped.", 131072), // 98
    p("shut-des.wav", "", "Coalition shuttle craft destroyed.", 131072), // 99
    p("tran-loc.wav", "", "Coalition transport located.", 131072), // 100
    p("tran-esc.wav", "", "Coalition transport escaped.", 131072), // 101
    p("tran-des.wav", "", "Coalition transport destroyed.", 131072), // 102
    p("transloc.wav", "", "Coalition transports located.", 131072), // 103
    p("transesc.wav", "", "Coalition transports escaped.", 131072), // 104
    p("transdes.wav", "", "Coalition transports destroyed.", 131072), // 105
    p("shiv-war.wav", "", "Warning! Engine core disabled.  Shiva destruction imminent.  Proceed to minimum safe distance.  Destruction in 30 seconds.", 131072), // 106
    p("spd-mine.wav", "", "Increase speed to deploy mine.", 131072), // 107
    p("hellrule.wav", "", "Hellbender Rules!", 131072), // 108
    p("hulldamg.wav", "", "Hull damage critical. Auto eject sequence activated.", 131072), // 109
    p("krak-des.wav", "", "Kraaken destroyed.", 131072), // 110
    p("kali-des.wav", "", "Kilimah destroyed.", 131072), // 111
    p("simi-des.wav", "", "Simian destroyed.", 131072), // 112
    p("nyx-des.wav", "", "Nyx destroyed.", 131072), // 113
    p("fx4-des.wav", "", "Fx4 destroyed.", 131072), // 114
    p("gaur-des.wav", "", "Guardian destroyed.", 131072), // 115
    p("krak-det.wav", "", "Kraaken detected.", 131072), // 116
    p("kali-det.wav", "", "Kilimah detected.", 131072), // 117
    p("simi-det.wav", "", "Simian detected.", 131072), // 118
    p("nyx-det.wav", "", "Nyx detected.", 131072), // 119
    p("fx4-det.wav", "", "Fx4 detected.", 131072), // 120
    p("gaur-det.wav", "", "Guardian detected.", 131072), // 121
    p("shk-des.wav", "", "Shock troops destroyed.", 131072), // 122
    p("trp-des.wav", "", "Troop transport destroyed.", 131072), // 123
    p("trps-des.wav", "", "Troop transports destroyed.", 131072), // 124
    p("trp-esc.wav", "", "Transport has escaped.", 131072), // 125
    p("shva-des.wav", "", "Shiva destroyed.", 131072), // 126
    p("shva-det.wav", "", "Shiva detected.", 131072), // 127
    p("opendiag.wav", "", "Welcome, Councilor.  I am Eve, the Hellbender's Enhanced Virtual Entity.  I am programmed to assist you in securing Coalition victory.  I will guide you through every battle -- but winning the war is up to you.", 131072), // 128
    p("gen-dest.wav", "", "Generator destroyed.", 131072), // 129
    p("plantdes.wav", "", "Power plant destroyed.", 131072), // 130
    p("nurs-des.wav", "", "Bion Nursery destroyed.", 131072), // 131
    p("radr-des.wav", "", "Radar destroyed.", 131072), // 132
    p("towr-des.wav", "", "Tower destroyed.", 131072), // 133
    p("surv-des.wav", "", "Surveillance tower destroyed.", 131072), // 134
    p("cont-des.wav", "", "Control tower destroyed.", 131072), // 135
    p("obsv-des.wav", "", "Observation Tower destroyed.", 131072), // 136
    p("comt-des.wav", "", "Communications destroyed.", 131072), // 137
    p("comc-des.wav", "", "Communications center destroyed.", 131072), // 138
    p("post-des.wav", "", "Listening post destroyed.", 131072), // 139
    p("con-des.wav", "", "Container destroyed.", 131072), // 140
    p("cons-des.wav", "", "Containers destroyed.", 131072), // 141
    p("cry-des.wav", "", "Cryogenic container destroyed.", 131072), // 142
    p("crys-des.wav", "", "Cryogenic containers destroyed.", 131072), // 143
    p("cryf-des.wav", "", "Cryogenic facility destroyed.", 131072), // 144
    p("citl-des.wav", "", "Citadel destroyed.", 131072), // 145
    p("arm-des.wav", "", "Armory destroyed.", 131072), // 146
    p("fact-des.wav", "", "Factory destroyed.", 131072), // 147
    p("bfal-des.wav", "", "Bion facility destroyed.", 131072), // 148
    p("resc-des.wav", "", "Research center destroyed.", 131072), // 149
    p("atmosdes.wav", "", "Atmospheric processor destroyed.", 131072), // 150
    p("contudes.wav", "", "Control unit destroyed.", 131072), // 151
    p("sat-des.wav", "", "Satellite destroyed.", 131072), // 152
    p("plat-des.wav", "", "Platform destroyed.", 131072), // 153
    p("hang-des.wav", "", "Hanger bay destroyed.", 131072), // 154
    p("mut-des.wav", "", "Mutation destroyed.", 131072), // 155
    p("frgt-des.wav", "", "Freighter destroyed.", 131072), // 156
    p("zone-30.wav", "", "Jump zone closing in 30 seconds.", 131072), // 157
    p("zone-25.wav", "", "Jump zone closing in 25 seconds.", 131072), // 158
    p("zone-20.wav", "", "Jump zone closing in 20 seconds.", 131072), // 159
    p("zone-des.wav", "", "Enemy jump zone controller destroyed.", 131072), // 160
    p("10-sec.wav", "", "10 seconds...", 131072), // 161
    p("9.wav", "", "9...", 131072), // 162
    p("8.wav", "", "8...", 131072), // 163
    p("7.wav", "", "7...", 131072), // 164
    p("6.wav", "", "6...", 131072), // 165
    p("5.wav", "", "5...", 131072), // 166
    p("4.wav", "", "4...", 131072), // 167
    p("3.wav", "", "3...", 131072), // 168
    p("2.wav", "", "2...", 131072), // 169
    p("1.wav", "", "1...", 131072), // 170
    p("0.wav", "", "0...", 131072), // 171
    p("zone-cls.wav", "", "Jump zone closed.", 131072), // 172
    p("dreams.wav", "", "In your dreams.", 131072), // 173
    p("knees.wav", "", "On your knees.", 131072), // 174
    p("hurt.wav", "", "Like that really hurt.", 131072), // 175
    p("stop.wav", "", "Don't!  Stop!", 131072), // 176
    p("threat.wav", "", "Are you threatening me?", 131072), // 177
    p("bite.wav", "", "Bite me!", 131072), // 178
    p("trigger.wav", "", "Try the trigger.", 131072), // 179
    p("luck.wav", "", "Better luck next time.", 131072), // 180
    p("payback.wav", "", "Payback time.", 131072), // 181
    p("giveitup.wav", "", "Give it up.", 131072), // 182
    p("didhurt.wav", "", "Did that hurt?", 131072), // 183
    p("ooh.wav", "", "Ooooh, you scare me.", 131072), // 184
    p("youwish.wav", "", "You wish!", 131072), // 185
    p("y-right.wav", "", "Yeah, right.", 131072), // 186
    p("setup-m.wav", "", "Welcome to Microsoft Hellbender Installation program.  Before continuing, close any open applications.", 131072), // 187
    p("setup-h.wav", "", "Welcome to Hellbender Installation Program.  Before continuing, close any open applications.", 131072), // 188
    p("setup-f.wav", "", "Setup will install Hellbender in the following destination folder.", 131072), // 189
    p("select-o.wav", "", "Select an installation option.", 131072), // 190
    p("quitsoon.wav", "", "Quitting so soon?", 131072), // 191
    p("seeyou.wav", "", "See you later.", 131072), // 192
    p("dataintr.wav", "", "Data transmission interrupted.", 131072), // 193
    p("dataeror.wav", "", "Data transmission did not complete due to an error.", 131072), // 194
    p("battle.wav", "", "Ready for battle?", 131072), // 195
    p("received.wav", "", "Council of Peace transmission received... Downloading data.", 131072), // 196
    p("complete.wav", "", "Data transmission complete.", 131072), // 197
    p("reac-des.wav", "", "Reactor destroyed.", 131072), // 198
    p("comm-des.wav", "", "Bion commando transports destroyed.", 131072), // 199
    p("fusn-des.wav", "", "Fusion reactor destroyed.", 131072), // 200
    p("cbasedes.wav", "", "Commando base destroyed.", 131072), // 201
    p("atmo-des.wav", "", "Atmospheric regulator destroyed.", 131072), // 202
    p("carg-des.wav", "", "Cargo transport destroyed.", 131072), // 203
    p("scon-des.wav", "", "Shipping containers destroyed.", 131072), // 204
    p("subs-des.wav", "", "Reactor substation destroyed.", 131072), // 205
    p("tcampdes.wav", "", "Commando training camp destroyed.", 131072), // 206
    p("mbasedes.wav", "", "Mining base destroyed.", 131072), // 207
    p("d12.wav", "", "Delta 12 generator destroyed.", 131072), // 208
    p("k7-des.wav", "", "Kelton 7 transport center destroyed.", 131072), // 209
    p("switch.wav", "", "Switch activated.", 131072), // 210
    p("relaydes.wav", "", "Relay station destroyed.", 131072), // 211
    p("mequ-des.wav", "", "Mining equipment destroyed.", 131072), // 212
    p("comrydes.wav", "", "Communications relay station destroyed.", 131072), // 213
    p("frig-des.wav", "", "Bion frigate destroyed.", 131072), // 214
    p("sent-des.wav", "", "Sentinel destroyed.", 131072), // 215
    p("worm-des.wav", "", "Wormhole stabilizer destroyed.", 131072), // 216
    p("tact-des.wav", "", "Tactical operations center destroyed.", 131072), // 217
    p("fcon-des.wav", "", "Fuel container destroyed.", 131072), // 218
    p("fconsdes.wav", "", "Fuel containers destroyed.", 131072), // 219
    p("conc-des.wav", "", "Control center destroyed.", 131072), // 220
    p("totc-des.wav", "", "Tactical operations training center destroyed.", 131072), // 221
    p("ctc-des.wav", "", "Commando training center destroyed.", 131072), // 222
    p("icn-dis.wav", "", "Interplanetary communications network disabled.", 131072), // 223
    p("cout-des.wav", "", "Communications outpost destroyed.", 131072), // 224
    p("bgt-des.wav", "", "Bion ground transport destroyed.", 131072), // 225
    p("pf-des.wav", "", "Power fluctuator destroyed.", 131072), // 226
    p("ecc-des.wav", "", "Eyrie command center destroyed.", 131072), // 227
    p("wt-des.wav", "", "Watchtower destroyed.", 131072), // 228
    p("lplt-des.wav", "", "Landing platform destroyed.", 131072), // 229
    p("nms-des.wav", "", "Nexus monitoring station destroyed.", 131072), // 230
    p("sts-des.wav", "", "Shock troop stronghold destroyed.", 131072), // 231
    p("secb-des.wav", "", "Security base destroyed.", 131072), // 232
    p("lpad-des.wav", "", "Launch pad destroyed.", 131072), // 233
    p("hydr-des.wav", "", "Hydrodynamic generator destroyed.", 131072), // 234
    p("tlp-des.wav", "", "Transport loading destroyed.", 131072), // 235
    p("pwrs-des.wav", "", "Power station destroyed.", 131072), // 236
    p("heg-des.wav", "", "Hydroelectric generator destroyed.", 131072), // 237
    p("agen-des.wav", "", "Auxilary generator destroyed.", 131072), // 238
    p("cps-des.wav", "", "Cenral power station destroyed.", 131072), // 239
    p("bfts-des.wav", "", "Bion fighter training school destroyed.", 131072), // 240
    p("bbar-des.wav", "", "Bion barracks destroyed.", 131072), // 241
    p("bsc-des.wav", "", "Bion fighter simulation center destroyed.", 131072), // 242
    p("lprt-des.wav", "", "Landing port destroyed.", 131072), // 243
    p("fhangdes.wav", "", "Fighter hanger destroyed.", 131072), // 244
    p("thangdes.wav", "", "Transport hanger destroyed.", 131072), // 245
    p("wtrc-des.wav", "", "Water control center destroyed.", 131072), // 246
    p("chps-des.wav", "", "Central hydroelectric power station destroyed.", 131072), // 247
    p("drsh-des.wav", "", "Druish fortress destroyed.", 131072), // 248
    p("ionc-des.wav", "", "Ionic turbines destroyed.", 131072), // 249
    p("hatc-des.wav", "", "Hatchery destroyed.", 131072), // 250
    p("munf-des.wav", "", "Munitions factory destroyed.", 131072), // 251
    p("repo-des.wav", "", "Genetic repository destroyed.", 131072), // 252
    p("enzm-des.wav", "", "Enzyme repository destroyed.", 131072), // 253
    p("gsf-des.wav", "", "Genetic storage facility destroyed.", 131072), // 254
    p("tfac-des.wav", "", "Transport facility destroyed.", 131072), // 255
    p("grf-des.wav", "", "Genetic research facility destroyed.", 131072), // 256
    p("gsc-des.wav", "", "Genetic storage center destroyed.", 131072), // 257
    p("sdep-des.wav", "", "Supply depot destroyed.", 131072), // 258
    p("sfac-des.wav", "", "Storage facility destroyed.", 131072), // 259
    p("cfac-des.wav", "", "Cloning facility destroyed.", 131072), // 260
    p("bgf-des.wav", "", "Biogenetic factory destroyed.", 131072), // 261
    p("bsf-des.wav", "", "Biogenetic storage facility destroyed.", 131072), // 262
    p("gob-des.wav", "", "Ground operations base destroyed.", 131072), // 263
    p("rfac-des.wav", "", "Research facility destroyed.", 131072), // 264
    p("tkrf-des.wav", "", "Thermokinetic research facility destroyed.", 131072), // 265
    p("tssa-des.wav", "", "Transport system staging area destroyed.", 131072), // 266
    p("rlab-des.wav", "", "Research laboratory destroyed.", 131072), // 267
    p("dna-des.wav", "", "DNA extraction facility destroyed.", 131072), // 268
    p("thal-des.wav", "", "Thalamus replication center destroyed.", 131072), // 269
    p("reco-des.wav", "", "Recombinant DNA laboratory destroyed.", 131072), // 270
    p("bay-des.wav", "", "Distribution bay destroyed.", 131072), // 271
    p("prot-des.wav", "", "Protein recombination unit destroyed.", 131072), // 272
    p("gerf-des.wav", "", "Genetic engineering research facility destroyed.", 131072), // 273
    p("aarc-des.wav", "", "Amino acid replication center destroyed.", 131072), // 274
    p("cmu-des.wav", "", "Cellular mutation unit destroyed.", 131072), // 275
    p("psf-des.wav", "", "Protein splicing facilities destroyed.", 131072), // 276
    p("liu-des.wav", "", "Laser integration unit destroyed.", 131072), // 277
    p("sent-des.wav", "", "Sentinel destroyed.", 131072), // 278
    p("sentry-d.wav", "", "Sentry destroyed.", 131072), // 279
    p("ffr-des.wav", "", "Force-field regenerator destroyed.", 131072), // 280
    p("cg-des.wav", "", "Cloaking generator destroyed.", 131072), // 281
    p("sc-des.wav", "", "Support craft destroyed.", 131072), // 282
    p("retu-des.wav", "", "Remote energy transfer units destroyed.", 131072), // 283
    p("wcu-des.wav", "", "Wormhole control units destroyed.", 131072), // 284
    p("ltwr-des.wav", "", "Lookout tower destroyed.", 131072), // 285
    p("ffr-des.wav", "", "Force-field regenerator destroyed.", 131072), // 286
    p("eds-des.wav", "", "Enemy docking station destroyed.", 131072), // 287
    p("cc-des.wav", "", "Communications conduits destroyed.", 131072), // 288
    p("ctf-des.wav", "", "Cloaking test facility destroyed.", 131072), // 289
    p("wrc-des.wav", "", "Weapons research center destroyed.", 131072), // 290
    p("lbasedes.wav", "", "Landing base destroyed.", 131072), // 291
    p("cow-des.wav", "", "Council of War destroyed.", 131072), // 292
    p("spid-des.wav", "", "Spiders destroyed.", 131072), // 293
    p("wtf-des.wav", "", "Weapons testing facility destroyed.", 131072), // 294
    p("nds-des.wav", "", "Nyx's docking station destroyed.", 131072), // 295
    p("ms-des.wav", "", "Morning Star destroyed.", 131072), // 296
    p("msds-des.wav", "", "Morning Star docking station destroyed.", 131072), // 297
    p("sb-des.wav", "", "Shuttle base destroyed.", 131072), // 298
    p("20-sec.wav", "", "20 seconds", 131072), // 299
];

/// A line by its number, if there is one.
pub fn phrase(id: usize) -> Option<&'static Phrase> {
    PHRASES.get(id)
}

/// A line by the sound it plays, which is how the engine finds one
/// (`0x4548a9` walks the table comparing `+0x14` with a file name).
///
/// This is what makes the level data speak: a `.NAV` point's completion
/// sound and a `.DEF` type's destruction sound are both file names, and the
/// words that go with them are in here rather than in the level. The first
/// match wins - a few sounds appear twice with the same words.
pub fn by_sound(sound: &str) -> Option<&'static Phrase> {
    let sound = sound.trim();
    PHRASES.iter().find(|p| p.sound.eq_ignore_ascii_case(sound))
}

