#!/usr/bin/env python3
"""The reference docs, as a folder.

`docs/README.md` is generated from the front matter of every page under
`docs/`, so the index cannot drift from the pages.

    tools/docs.py index    regenerate docs/README.md
    tools/docs.py check    front matter complete, status known, index current,
                           relative links resolve
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
INDEX = DOCS / "README.md"

STATUS = ["solid", "partial", "guess"]

SECTIONS = [
    ("formats", "File formats", "The containers and record layouts."),
    ("engine", "Engine", "How the game works, subsystem by subsystem."),
    ("content", "Content", "What is actually in the archives."),
    ("port", "Port", "The Rust port: architecture, staging, status."),
]

HEADER = """# Hellbender reference

What is true about Hellbender (Microsoft / Terminal Reality, 1996), written for
someone who wants to write a parser or a subsystem. Generated by
`tools/docs.py index` - edit the pages, not this file.

The [worklog](../WORKLOG.md) is the other half: it says how each of these was
worked out. `status` below is the honesty knob - `solid` means every field is
accounted for, `partial` means named unknowns remain, `guess` means a hypothesis
nobody has knocked down yet.
"""


def front_matter(path: pathlib.Path) -> dict:
    text = path.read_text()
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}
    out = {}
    for line in text[4:end].splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            out[key.strip()] = value.strip()
    return out


def pages(section: str) -> list[tuple[pathlib.Path, dict]]:
    found = []
    for path in sorted((DOCS / section).glob("*.md")):
        found.append((path, front_matter(path)))
    return found


def render_index() -> str:
    lines = [HEADER]
    for section, heading, blurb in SECTIONS:
        found = pages(section)
        if not found:
            continue
        lines.append(f"\n## {heading}\n\n{blurb}\n")
        lines.append("\n| Page | Status | Covers |\n| --- | --- | --- |\n")
        for path, meta in found:
            title = meta.get("title", path.stem).replace("|", "\\|")
            covers = meta.get("covers", "").replace("|", "\\|")
            lines.append(
                f"| [{title}]({section}/{path.name}) "
                f"| {meta.get('status', '?')} | {covers} |\n"
            )
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("index")
    sub.add_parser("check")
    args = parser.parse_args()

    if args.command == "index":
        INDEX.write_text(render_index())
        total = sum(len(pages(s)) for s, _, _ in SECTIONS)
        print(f"{total} pages -> docs/README.md")
        return 0

    problems = []
    for section, _, _ in SECTIONS:
        for path, meta in pages(section):
            where = path.relative_to(ROOT)
            for wanted in ("title", "status", "covers"):
                if not meta.get(wanted):
                    problems.append(f"{where} has no {wanted}")
            if meta.get("status") and meta["status"] not in STATUS:
                problems.append(
                    f"{where}: unknown status {meta['status']!r}; "
                    f"one of {', '.join(STATUS)}"
                )
            # A dead cross-link in a reference page sends the reader looking
            # for a page that was renamed or never written.
            for target in re.findall(r"\]\(([^)#:]+\.md)[^)]*\)", path.read_text()):
                if not (path.parent / target).resolve().exists():
                    problems.append(f"{where}: dead link to {target}")
    if not INDEX.exists() or INDEX.read_text() != render_index():
        problems.append("docs/README.md is stale - run `tools/docs.py index`")

    for problem in problems:
        print(problem, file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
