#!/usr/bin/env python3
"""The worklog, as a folder.

One entry per file under `worklog/`, named `NNNN-slug.md`, with the metadata in
front matter so it can be read without opening the prose. `WORKLOG.md` is the
index and is generated from those files, never edited by hand.

    tools/worklog.py next            the number the next entry takes
    tools/worklog.py new "<title>" --area <area> [--files a,b]
    tools/worklog.py index           regenerate WORKLOG.md
    tools/worklog.py check           index is current and numbering is sound
"""

import argparse
import datetime
import pathlib
import re
import sys
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parent.parent
DIR = ROOT / "worklog"
INDEX = ROOT / "WORKLOG.md"

AREAS = [
    "format",   # a container or record layout decoded
    "decomp",   # facts pulled out of HELLBEND.EXE itself
    "engine",   # game loop, entity model, simulation rules
    "render",   # rasteriser, texturing, palettes, the sky
    "world",    # terrain, levels, collision, missions
    "flight",   # ship physics, controls, weapons
    "audio",    # music, sound effects, the mixer
    "video",    # Smacker cutscenes
    "net",      # DirectPlay multiplayer
    "ui",       # menus, HUD, cockpit, fonts
    "content",  # what is actually in the PODs, inventories, counts
    "port",     # Rust port architecture and progress
    "tooling",  # the extractors and viewers under tools/
    "build",    # cargo, layout, CI
    "test",     # harnesses and fixtures
]

HEADER = """# Worklog

Running engineering log for the Hellbender reverse engineering and Rust port.
One file per entry under
[`worklog/`](worklog/), newest at the bottom. This index is generated by
`tools/worklog.py index` - edit the entries, not this file.

Code says what; the worklog says *how we found out* and *why it is that way*.
"""


def slug(title: str) -> str:
    text = unicodedata.normalize("NFKD", title).encode("ascii", "ignore").decode()
    text = re.sub(r"[^A-Za-z0-9]+", "-", text).strip("-").lower()
    return re.sub(r"-+", "-", text)[:60].strip("-")


def front_matter(path: pathlib.Path) -> dict:
    text = path.read_text()
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}
    out = {}
    for line in text[4:end].splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            out[key.strip()] = value.strip()
    return out


def entries() -> list[tuple[pathlib.Path, dict]]:
    found = []
    for path in sorted(DIR.glob("*.md")):
        meta = front_matter(path)
        if meta.get("number"):
            found.append((path, meta))
    return found


def next_number() -> int:
    """The next entry's number, without reading a single entry's prose.

    From the filenames, so it stays cheap however long the log gets.
    """
    numbers = [
        int(m.group(1))
        for path in DIR.glob("*.md")
        if (m := re.match(r"(\d+)-", path.name))
    ]
    return max(numbers, default=0) + 1


def render_index() -> str:
    lines = [HEADER]
    by_area: dict[str, int] = {}
    for _, meta in entries():
        for area in (a.strip() for a in meta.get("area", "?").split(",")):
            by_area[area] = by_area.get(area, 0) + 1
    counted = ", ".join(f"{area} {n}" for area, n in sorted(by_area.items()))
    total = len(entries())
    lines.append(f"\n{total} entries: {counted}.\n")
    lines.append("\n| # | Entry | Date | Area |\n| ---: | --- | --- | --- |\n")
    for path, meta in entries():
        title = meta.get("title", path.stem).replace("|", "\\|")
        lines.append(
            f"| {meta['number']} | [{title}](worklog/{path.name}) "
            f"| {meta.get('date', '')} | {meta.get('area', '')} |\n"
        )
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("next")
    sub.add_parser("index")
    sub.add_parser("check")
    make = sub.add_parser("new")
    make.add_argument("title")
    make.add_argument(
        "--area",
        required=True,
        help="one of " + ", ".join(AREAS) + "; several may be given, comma separated",
    )
    make.add_argument("--files", default="")
    args = parser.parse_args()

    if args.command == "next":
        print(next_number())
        return 0

    if args.command == "index":
        INDEX.write_text(render_index())
        print(f"{len(entries())} entries -> {INDEX.name}")
        return 0

    if args.command == "check":
        found = entries()
        numbers = [int(meta["number"]) for _, meta in found]
        problems = []
        if len(set(numbers)) != len(numbers):
            duplicated = sorted({n for n in numbers if numbers.count(n) > 1})
            problems.append(f"repeated numbers: {duplicated}")
        for path, meta in found:
            if not path.name.startswith(f"{int(meta['number']):04d}-"):
                problems.append(f"{path.name} is filed under a different number")
            for wanted in ("title", "date", "area"):
                if not meta.get(wanted):
                    problems.append(f"{path.name} has no {wanted}")
            # An entry may sit in more than one area: porting a skill is
            # server work and content work at once, and saying so is truer
            # than picking whichever one it was mostly.
            for area in (a.strip() for a in meta.get("area", "").split(",")):
                if area and area not in AREAS:
                    problems.append(f"{path.name}: unknown area {area!r}")
        if INDEX.read_text() != render_index():
            problems.append("WORKLOG.md is stale - run `tools/worklog.py index`")
        for problem in problems:
            print(problem, file=sys.stderr)
        return 1 if problems else 0

    for area in (a.strip() for a in args.area.split(",")):
        if area not in AREAS:
            print(f"unknown area {area!r}; one of {', '.join(AREAS)}", file=sys.stderr)
            return 2

    number = next_number()
    path = DIR / f"{number:04d}-{slug(args.title)}.md"
    files = "\n".join(f"files: {args.files}" for _ in [1] if args.files)
    path.write_text(
        f"---\nnumber: {number}\ntitle: {args.title}\n"
        f"date: {datetime.date.today()}\narea: {args.area}\n"
        + (files + "\n" if files else "")
        + f"---\n\n# {number}. {args.title}\n\n\n\n**Still unknown:** \n"
    )
    INDEX.write_text(render_index())
    print(path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
